import type { CSSProperties } from "react";

export const S: Record<string, CSSProperties> = {
  root: { display:"flex", flexDirection:"column", height:"100dvh", background:"#dbeafe", fontFamily:"'Noto Sans JP','Hiragino Kaku Gothic ProN',sans-serif", maxWidth:520, margin:"0 auto", position:"relative", overflow:"hidden" },
  header: { display:"flex", alignItems:"center", justifyContent:"space-between", padding:"14px 20px 10px", flexShrink:0 },
  menuBtn: { width:40, height:40, background:"white", border:"none", borderRadius:12, cursor:"pointer", display:"flex", alignItems:"center", justifyContent:"center", boxShadow:"0 1px 4px rgba(0,0,0,0.08)" },
  chatArea: { flex:1, overflowY:"auto", padding:"8px 16px 8px", display:"flex", flexDirection:"column", gap:10 },

  emptyState: { width:"100%", padding:"20px 0 40px", display:"flex", flexDirection:"column", alignItems:"center", animation:"fadeIn 0.4s ease" },
  exampleBtn: { width:"100%", background:"white", border:"none", borderRadius:16, padding:"13px 16px", fontSize:14, color:"#334155", cursor:"pointer", fontFamily:"inherit", textAlign:"left", lineHeight:1.5, boxShadow:"0 1px 3px rgba(0,0,0,0.06)", marginBottom:8 },
  suggestChip: { flexShrink:0, background:"white", border:"1.5px solid #e2e8f0", borderRadius:20, padding:"8px 14px", fontSize:13, color:"#475569", cursor:"pointer", fontFamily:"inherit", fontWeight:600, whiteSpace:"nowrap", boxShadow:"0 1px 3px rgba(0,0,0,0.06)", transition:"border-color 0.15s" },
  roleHint: { display:"flex", gap:8, padding:"6px 0", alignItems:"flex-start", borderBottom:"1px solid #e2e8f0" },

  msgTs: { fontSize: 10, color: "#94a3b8", textAlign: "left", marginBottom: 3, paddingLeft: 2 },
  msgTsRight: { fontSize: 10, color: "#94a3b8", textAlign: "right", marginBottom: 3, paddingRight: 4 },
  userBubble: { alignSelf:"flex-end", background:"white", borderRadius:"18px 18px 4px 18px", padding:"11px 16px", fontSize:15, color:"#1e293b", maxWidth:"78%", lineHeight:1.6, boxShadow:"0 1px 3px rgba(0,0,0,0.07)", animation:"fadeIn 0.2s ease" },
  noticeBubble: { alignSelf:"center", background:"#fef3c7", borderRadius:12, padding:"10px 16px", fontSize:14, color:"#92400e", maxWidth:"85%", lineHeight:1.5, textAlign:"center" },

  card: { alignSelf:"flex-start", background:"white", borderRadius:"4px 18px 18px 18px", padding:"16px 16px 14px", maxWidth:"93%", boxShadow:"0 1px 4px rgba(0,0,0,0.08)", animation:"fadeIn 0.25s ease", transition:"outline 0.1s", width:"100%" },
  cardAction: { fontSize:18, fontWeight:800, color:"#0f172a", lineHeight:1.45, marginBottom:10 },

  proGroup: { width:"100%", display:"flex", flexDirection:"column", gap:8, animation:"fadeIn 0.3s ease" },
  proGroupLabel: { display:"flex", alignItems:"center", gap:7, fontSize:13, color:"#94a3b8", fontWeight:700, textTransform:"uppercase", letterSpacing:"0.07em", paddingLeft:4 },
  proGroupDot: { width:6, height:6, borderRadius:"50%", background:"#2563eb" },
  roadmapCard: { background:"white", borderRadius:14, padding:"12px 14px", border:"1px solid #dbeafe", marginBottom:4 },
  roadmapRow: { display:"flex", flexDirection:"column", gap:4, marginBottom:6 },
  roadmapLabel: { fontSize:10, fontWeight:700, color:"#2563eb", textTransform:"uppercase", letterSpacing:"0.07em" },
  roadmapText: { fontSize:14, color:"#1e293b", fontWeight:600, lineHeight:1.6 },
  summaryText: { fontSize:13, color:"#64748b", lineHeight:1.6, borderTop:"1px solid #e2e8f0", paddingTop:8, marginTop:4 },
  stepHeader: { display:"flex", alignItems:"center", gap:4, marginBottom:8 },
  stepDot: { width:8, height:8, borderRadius:"50%", flexShrink:0, transition:"background 0.3s" },
  stepAction: { fontSize:18, fontWeight:800, color:"#0f172a", lineHeight:1.4, marginBottom:10 },
  stepsPreview: { background:"#f8fafc", borderRadius:10, padding:"8px 10px", marginBottom:10, display:"flex", flexDirection:"column", gap:5 },
  stepsPreviewRow: { display:"flex", alignItems:"center", gap:6 },
  stepsPreviewNum: { width:16, height:16, borderRadius:"50%", fontSize:9, fontWeight:800, display:"flex", alignItems:"center", justifyContent:"center", flexShrink:0 },
  stepsPreviewTxt: { flex:1, fontSize:12, color:"#475569", lineHeight:1.4 },
  stepsPreviewTime: { fontSize:10, color:"#94a3b8", flexShrink:0 },
  proCardCompact: { background:"white", borderRadius:"4px 14px 14px 14px", padding:"11px 13px", border:"none", borderLeft:"3px solid", cursor:"pointer", width:"100%", fontFamily:"inherit", textAlign:"left", boxShadow:"0 1px 3px rgba(0,0,0,0.07)", transition:"box-shadow 0.15s" },
  proCard: { background:"white", borderRadius:"4px 14px 14px 14px", padding:"14px 14px 12px", boxShadow:"0 1px 4px rgba(0,0,0,0.08)", borderLeft:"3px solid", transition:"outline 0.1s" },
  proRoleTag: { display:"flex", alignItems:"center", gap:6, fontSize:13, fontWeight:800, textTransform:"uppercase", letterSpacing:"0.07em", marginBottom:8 },
  proRoleEn: { fontSize:11, fontWeight:500, color:"#94a3b8", textTransform:"none", letterSpacing:0, marginLeft:2 },
  proAction: { fontSize:16, fontWeight:800, color:"#0f172a", lineHeight:1.45, marginBottom:8 },

  metaRow: { display:"flex", alignItems:"center", gap:10, flexWrap:"wrap", marginBottom:8 },
  minPill: { fontSize:13, fontWeight:700, borderRadius:20, padding:"3px 12px", flexShrink:0 },
  reasonTxt: { fontSize:14, color:"#64748b", lineHeight:1.5, flex:1 },
  nextTxt: { fontSize:14, color:"#94a3b8", marginBottom:14, lineHeight:1.5, fontStyle:"italic" },

  primaryBtn: { border:"none", borderRadius:12, padding:"13px 0", fontWeight:800, fontSize:15, color:"white", cursor:"pointer", fontFamily:"inherit" },
  subRow: { display:"flex", gap:8 },
  subBtn: { flex:1, background:"white", border:"1px solid #cbd5e1", borderRadius:10, padding:"9px 0", fontSize:14, color:"#334155", cursor:"pointer", fontFamily:"inherit", fontWeight:700 },
  btnRow: { display:"flex", gap:8, alignItems:"stretch" },
  ghostBtn: { flex:1, background:"#f1f5f9", border:"none", borderRadius:12, padding:"13px 0", fontSize:14, color:"#475569", cursor:"pointer", fontFamily:"inherit", fontWeight:700 },
  pendBtnLg: { flex:1, background:"#f1f5f9", border:"2px solid #e2e8f0", borderRadius:12, padding:"13px 0", fontSize:14, color:"#475569", cursor:"pointer", fontFamily:"inherit", fontWeight:700 },
  retryBtnFull: { width:"100%", background:"transparent", border:"1px solid #e2e8f0", borderRadius:12, padding:"10px 0", fontSize:14, color:"#94a3b8", cursor:"pointer", fontFamily:"inherit", fontWeight:600, marginTop:8 },
  supplementBtn: { width:"100%", background:"transparent", border:"1px dashed #cbd5e1", borderRadius:10, padding:"9px 0", fontSize:14, color:"#64748b", cursor:"pointer", fontFamily:"inherit", fontWeight:600, marginTop:8 },
  detailToggle: { background:"transparent", border:"none", fontSize:13, color:"#94a3b8", cursor:"pointer", fontFamily:"inherit", fontWeight:600, padding:"4px 0", marginBottom:6, display:"block" },
  detailPanel: { background:"#f8fafc", borderRadius:10, padding:"10px 12px", display:"flex", flexDirection:"column", gap:7 },
  detailRow: { display:"flex", alignItems:"flex-start", gap:6 },
  detailIcon: { fontSize:12, flexShrink:0, marginTop:1 },
  detailTxt: { fontSize:13, color:"#475569", lineHeight:1.55 },
  contextBubble: { background:"white", borderRadius:14, padding:"12px 14px", border:"1px solid #e2e8f0", marginBottom:4, animation:"fadeIn 0.3s ease" },
  contextHeader: { display:"flex", alignItems:"flex-start", gap:8, marginBottom:6 },
  contextIcon: { fontSize:16, flexShrink:0 },
  contextTitle: { fontSize:14, fontWeight:700, color:"#1e293b" },
  contextMeta: { fontSize:13, color:"#94a3b8", marginTop:1 },
  contextToggle: { background:"transparent", border:"1px solid #e2e8f0", borderRadius:8, padding:"3px 8px", fontSize:11, color:"#64748b", cursor:"pointer", fontFamily:"inherit", fontWeight:600, flexShrink:0 },
  contextPrompt: { fontSize:12, color:"#475569", background:"#f8fafc", borderRadius:8, padding:"5px 8px", marginBottom:6, lineHeight:1.5 },
  contextHistory: { borderLeft:"2px solid #e2e8f0", paddingLeft:10, display:"flex", flexDirection:"column", gap:6, marginTop:6 },
  contextRow: { display:"flex", gap:6, alignItems:"flex-start" },
  contextRowIcon: { fontSize:11, flexShrink:0, marginTop:1 },
  contextRowText: { fontSize:11, lineHeight:1.6 },
  confirmDialog: { position:"absolute", bottom:0, left:0, right:0, background:"white", borderRadius:"24px 24px 0 0", padding:"24px 20px 40px", zIndex:21, boxShadow:"0 -4px 24px rgba(0,0,0,0.12)", animation:"slideUp 0.25s ease" },
  confirmTitle: { fontSize:17, fontWeight:800, color:"#0f172a", marginBottom:10 },
  confirmBody: { fontSize:14, color:"#334155", lineHeight:1.7, marginBottom:12 },
  supplementArea: { width:"100%", background:"#f8fafc", border:"1px solid #e2e8f0", borderRadius:12, padding:"11px 14px", color:"#1e293b", fontSize:14, lineHeight:1.6, outline:"none", resize:"none", fontFamily:"inherit", marginBottom:10, display:"block" },

  progressTrack: { height:4, background:"#e2e8f0", borderRadius:2, overflow:"hidden", marginBottom:12 },
  progressFill: { height:"100%", borderRadius:2, transition:"width 0.5s linear, background 0.3s" },
  timerRow: { display:"flex", justifyContent:"space-between", alignItems:"flex-start", marginBottom:12 },
  timerCell: { display:"flex", flexDirection:"column", alignItems:"flex-start" },
  timerBig: { fontSize:26, fontWeight:900, fontVariantNumeric:"tabular-nums", lineHeight:1 },
  timerSub: { fontSize:10, color:"#94a3b8", marginTop:3, fontWeight:600, textTransform:"uppercase", letterSpacing:"0.06em" },
  timerDisplay: { display:"flex", alignItems:"center", justifyContent:"space-between", marginBottom:12 },
  timerHalf: { display:"flex", flexDirection:"column", alignItems:"flex-start", flex:1 },
  timerDivider: { width:1, height:36, background:"#e2e8f0", margin:"0 12px" },
  resolvedRow: { display:"flex", alignItems:"center", gap:10, flexWrap:"wrap", marginTop:4 },
  resolvedSub: { fontSize:13, color:"#94a3b8" },
  goalRow: { display:"flex", alignItems:"flex-start", gap:6, background:"#f0fdf4", borderRadius:10, padding:"7px 10px", marginBottom:8 },
  goalIcon: { fontSize:13, flexShrink:0 },
  goalTxt: { fontSize:13, color:"#166534", lineHeight:1.5, fontWeight:600 },
  tipsRow: { display:"flex", alignItems:"flex-start", gap:6, background:"#fffbeb", borderRadius:10, padding:"7px 10px", marginBottom:8 },
  tipsIcon: { fontSize:13, flexShrink:0 },
  tipsTxt: { fontSize:14, color:"#92400e", lineHeight:1.55 },
  toolsRow: { display:"flex", alignItems:"flex-start", gap:6, background:"#f8fafc", borderRadius:10, padding:"7px 10px", marginBottom:10 },
  toolsIcon: { fontSize:14, flexShrink:0 },
  toolsTxt: { fontSize:13, color:"#475569", lineHeight:1.5 },

  loadingWrap: { alignSelf:"flex-start", display:"flex", alignItems:"center", gap:5, background:"white", borderRadius:"4px 18px 18px 18px", padding:"14px 18px", boxShadow:"0 1px 3px rgba(0,0,0,0.06)" },
  dot: { width:7, height:7, background:"#94a3b8", borderRadius:"50%", display:"inline-block", animation:"blink 1.2s infinite" },

  inputBar: { padding:"8px 16px 24px", flexShrink:0 },
  inputCard: { display:"flex", alignItems:"center", gap:8, background:"white", borderRadius:20, padding:"10px 10px 10px 16px", boxShadow:"0 2px 8px rgba(0,0,0,0.08)", transition:"box-shadow 0.2s" },
  textarea: { flex:1, background:"transparent", border:"none", outline:"none", color:"#1e293b", fontSize:15, resize:"none", lineHeight:1.6, minHeight:26, maxHeight:120, overflow:"auto" },
  sendBtn: { width:38, height:38, flexShrink:0, border:"none", borderRadius:12, color:"white", fontSize:18, fontWeight:900, cursor:"pointer", display:"flex", alignItems:"center", justifyContent:"center", transition:"opacity 0.2s" },

  overlay: { position:"absolute", inset:0, background:"rgba(15,23,42,0.25)", zIndex:20 },
  drawer: { position:"absolute", top:0, left:0, bottom:0, width:300, background:"white", zIndex:21, padding:"56px 12px 40px", animation:"slideIn 0.25s ease", boxShadow:"4px 0 24px rgba(0,0,0,0.1)", borderRadius:"0 24px 24px 0", overflowY:"auto" },
  drawerSection: { fontSize:11, fontWeight:700, color:"#94a3b8", textTransform:"uppercase", letterSpacing:"0.08em", padding:"0 8px 10px" },
  drawerItem: { width:"100%", display:"flex", alignItems:"center", gap:12, padding:"12px 10px", border:"1px solid transparent", borderRadius:14, cursor:"pointer", fontFamily:"inherit", background:"transparent", marginBottom:4 },
  drawerItemActive: { background:"#2563eb08", borderColor:"#2563eb33" },
  modeIcon: { width:40, height:40, borderRadius:12, display:"flex", alignItems:"center", justifyContent:"center", flexShrink:0 },
  drawerName: { fontSize:14, fontWeight:800, marginBottom:2 },
  drawerSub: { fontSize:13, color:"#94a3b8", lineHeight:1.5 },
  drawerSubLink: { width:"100%", background:"transparent", border:"none", padding:"8px 10px", fontSize:13, color:"#94a3b8", cursor:"pointer", fontFamily:"inherit", textAlign:"left" },
  drawerDivider: { height:1, background:"#f1f5f9", margin:"10px 8px" },
  roleListItem: { display:"flex", gap:10, padding:"8px 10px", alignItems:"flex-start" },

  sheet: { position:"absolute", bottom:0, left:0, right:0, background:"white", borderRadius:"24px 24px 0 0", padding:"12px 20px 40px", zIndex:21, animation:"slideUp 0.25s ease", maxHeight:"82dvh", overflowY:"auto", boxShadow:"0 -4px 24px rgba(0,0,0,0.1)" },
  sheetHandle: { width:36, height:4, background:"#e2e8f0", borderRadius:2, margin:"0 auto 16px" },
  sheetHeader: { display:"flex", justifyContent:"space-between", alignItems:"center", marginBottom:16 },
  sheetTitle: { fontSize:17, fontWeight:800, color:"#0f172a" },
  closeBtn: { background:"transparent", border:"none", color:"#94a3b8", fontSize:18, cursor:"pointer" },

  pendCard: { background:"white", borderRadius:16, padding:14, marginBottom:10, border:"1px solid #e2e8f0", boxShadow:"0 1px 4px rgba(0,0,0,0.06)" },

  editLabel: { display:"block", fontSize:12, fontWeight:700, color:"#64748b", marginBottom:6, textTransform:"uppercase", letterSpacing:"0.05em" },
  editInput: { width:"100%", background:"#f8fafc", border:"1px solid #e2e8f0", borderRadius:12, padding:"11px 14px", color:"#1e293b", fontSize:14, outline:"none", fontFamily:"inherit", marginBottom:14, display:"block" },
};
